version: '3'
services:
  app:
    build:
      context: https://github.com/stepinus/coolify_apps.git
    volumes:
      - /data/coolify/templates:/data/coolify/templates
    ports:
      - "3000:3000"
    environment:
      NEXTAUTH_SECRET: your_nextauth_secret
