version: '3.8'

services:
  nextjs:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXTAUTH_SECRET=your_super_secret_key
      - NEXTAUTH_URL=http://localhost:3000
    volumes:
      # Линковка темплейтов
      - /data/coolify/templates:/data/coolify/templates
      # Персистентное хранение
      - nextjs-data:/app/.next/cache
      
volumes:
  nextjs-data:
